POST  http://localhost:3000/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGFmN2ZmYS1iZDdlLTQ5M2MtYmU3Yi04Y2E3Yjg1MmFiNGIiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTg0MTM4NX0.thkSahybCqqHZMB0FAvB8vUpV4nR_ACTYHf_yvP8fL0

{
  "title": "Curso de Reactjs aaaDeus12",
  "description": "Descrição do aaaaCurso de Reactjs Deus1"
}

###

GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/3df46b01-7cbc-4134-87f6-5d34fe11f501
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGFmN2ZmYS1iZDdlLTQ5M2MtYmU3Yi04Y2E3Yjg1MmFiNGIiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NTgzODUyMX0.tLO9XOoRCTKqfbu2VdRW0yFJb59ETG5cYbrGKI-6aFo

###

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "heitor.franco6@live.com",
  "password": "123456"
}
